# Generated by Django 4.1.3 on 2022-11-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CartImage', models.ImageField(upload_to='images/')),
                ('CartTitle', models.CharField(max_length=100)),
                ('CartDescription', models.CharField(max_length=250)),
                ('CartBtnTitle', models.CharField(max_length=50)),
            ],
        ),
    ]
