# Generated by Django 4.1.3 on 2022-11-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': ' ماشین ها', 'verbose_name_plural': 'ماشین ها'},
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='CartBtnTitle',
            field=models.CharField(max_length=50, verbose_name='فروشی یا اجاره ایی؟'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='CartDescription',
            field=models.CharField(max_length=250, verbose_name='توضیحات ماشین'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='CartImage',
            field=models.ImageField(upload_to="{% static 'images/'%}", verbose_name='عکس ماشین'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='CartTitle',
            field=models.CharField(max_length=100, verbose_name='اسم ماشین'),
        ),
    ]
