# Generated by Django 4.1.3 on 2022-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_cartmodel_options_alter_cartmodel_cartbtntitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='CartImage',
            field=models.ImageField(upload_to="{'images/'}", verbose_name='عکس ماشین'),
        ),
    ]
