# Generated by Django 4.1.3 on 2022-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_cartmodel_cartimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='CartImage',
            field=models.ImageField(upload_to='media/', verbose_name='عکس ماشین'),
        ),
    ]
