# Generated by Django 4.1.3 on 2022-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_motortmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motortmodel',
            name='MotorBtnTitle',
        ),
        migrations.AddField(
            model_name='motortmodel',
            name='BuyOption',
            field=models.IntegerField(choices=[('Sold', 'فروشی'), ('Rent', 'اجاره ایی')], null=True),
        ),
    ]
